### ISSUE TITLE
[JetNews]: Address Roboelectric version todo

### ISSUE THREAD

**Issue by florina-muntenescu** [android/compose-samples#896]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is there a StackOverflow question about this issue?

- [X] I have searched StackOverflow

### Is this an issue related to one of the samples?

- [X] Yes, this is a specific issue related to this samples repo.

### Sample app

JetNews

### What happened?

Address TODO:

Bump to 4.6.* after https://github.com/robolectric/robolectric/issues/6593 is fixed

The referenced issue is now closed

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct
